In [35]:
from arcgis.gis import GIS
from arcgis.mapping import VectorTileLayer, WebMap
from arcgis.features import FeatureLayer
from arcgis.geometry import Point
from arcgis.geometry.filters import intersects

In [2]:
gis = GIS()
wmap = gis.map()

WHO_VTL_URL="https://tiles.arcgis.com/tiles/5T5nSi527N4F7luB/arcgis/rest/services/WHO_Polygon_Basemap_Disputed_Areas_and_Borders_VTP/VectorTileServer"
disputed_areas_vtl = VectorTileLayer(WHO_VTL_URL)

wmap.add_layer(disputed_areas_vtl)

wmap

MapView(layout=Layout(height='400px', width='100%'))

In [3]:
WHO_FL_URL = "https://services.arcgis.com/5T5nSi527N4F7luB/arcgis/rest/services/DISPUTED_AREAS_mask/FeatureServer/0"
disputed_areas_fl = FeatureLayer(WHO_FL_URL)

for f in disputed_areas_fl.properties.fields:
    print(f['name'])
    
disputed_areas_fl.query().sdf

OBJECTID
NAME
EndDate
StartDate
Shape__Area
Shape__Length

,OBJECTID,NAME,EndDate,StartDate,Shape__Area,Shape__Length,SHAPE
0,15,Jammu and Kashmir,1970-01-03 22:23:22.214400,2000-01-01,18.428927,26.734759,"{""rings"": [[[74.8175048830001, 37.021911621000..."
1,16,Lake Albert,1970-01-03 22:23:22.214400,2000-01-01,0.451467,3.876805,"{""rings"": [[[31.3736090900001, 2.1922181820000..."
2,17,Lake Victoria,1970-01-03 22:23:22.214400,2000-01-01,5.591845,19.091888,"{""rings"": [[[33.1876363640001, 0.4263272730000..."
3,18,Lake Tanganyika,1970-01-03 22:23:22.214400,2000-01-01,2.686102,14.427743,"{""rings"": [[[29.186327272, -5.91204545499994],..."
4,19,Lake Malawi,1970-01-03 22:23:22.214400,2000-01-01,2.409741,12.272866,"{""rings"": [[[34.2885131840001, -9.700378417999..."
5,20,Aral Sea,1970-01-03 22:23:22.214400,2000-01-01,2.528480,15.231046,"{""rings"": [[[58.8362727270001, 45.015627272000..."
6,21,Great Lakes of NA,1970-01-03 22:23:22.214400,2000-01-01,23.444515,73.180019,"{""rings"": [[[-84.4883818179999, 46.44420000000..."
7,22,Great Lakes of NA,1970-01-03 22:23:22.214400,2000-01-01,2.192864,12.360113,"{""rings"": [[[-79.062145455, 43.2723363630001],..."
8,23,Great Lakes of NA,1970-01-03 22:23:22.214400,2000-01-01,2.828093,12.171750,"{""rings"": [[[-78.902218182, 42.9197181820001],..."
9,24,Lake Titicaca,1970-01-03 22:23:22.214400,2000-01-01,0.654223,7.661652,"{""rings"": [[[-69.845236364, -15.879845455], [-..."
10,25,Aksai Chin,1970-01-03 22:23:22.214400,2000-01-01,2.959258,10.169416,"{""rings"": [[[79.4458160400001, 35.951385498], ..."
11,26,Abyei,1970-01-03 22:23:22.214400,2011-07-11,0.869880,3.693940,"{""rings"": [[[28.268920898, 9.34613037100007], ..."
12,27,Western Sahara,1970-01-03 22:23:22.214400,2000-01-01,24.003663,28.783563,"{""rings"": [[[-13.1668090819999, 27.66650390600..."
13,28,Golan,1970-01-03 22:23:22.214400,2000-01-01,0.110430,1.737932,"{""rings"": [[[35.7739669160001, 33.334069653], ..."

In [5]:
# Pin in Kashmir
pin_lng, pin_lat = 74.80611, 34.09111
pin = Point({"x" : pin_lng, "y" : pin_lat})

# Pin in Long beach
pin2_lng, pin2_lat = -118.15, 33.80
pin2 = Point({"x" : pin2_lng, "y" : pin2_lat})

pin3_lng, pin3_lat = -12.553, 22.7325
pin3 = Point({"x" : pin3_lng, "y" : pin3_lat})

In [41]:
# construct a geometry filter to check if each point is in a disputed area
pin_filter = intersects(pin)
pin2_filter = intersects(pin2)
pin3_filter = intersects(pin3)

from random import random
from time import time

start = time()

# pin1 is in a disputed area, pin3 intersects a disputed area
for i in range(500):
    pin = Point({"x" : random()*100, "y" : random()*100})
    num_errors = 0
    pin_filter = intersects(pin)
    success = False
    while not success:
        try:
            print(len(disputed_areas_fl.query(geometry_filter=pin_filter, return_geometry=False).features))
            success = True
        except Exception as e:
            print("ERROR")
            num_errors += 1
        finally:
            if num_errors > 5:
                break

stop = time()
print(stop - start)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
ERROR
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
181.52287793159485